name: Auto Blogger

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 오전 9시(한국시간)에 자동 실행
  workflow_dispatch:      # 수동 실행 버튼도 허용

jobs:
  autopost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run Auto Posting Script
        env:
          BLOG_ID: ${{ secrets.BLOG_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python main.py
